### ISSUE TITLE
Atualizar 01-Documentação de Contexto.md de acordo com o documento do Projeto

### ISSUE THREAD

**Issue by caarlos1** [ICEI-PUC-Minas-PMV-ADS/pmv-ads-2023-2-e1-proj-web-t5-doe-facil#2]
Link do arquivo a ser editado:
https://github.com/ICEI-PUC-Minas-PMV-ADS/pmv-ads-2023-2-e1-proj-web-t5-doe-facil/blob/main/documentos/01-Documenta%C3%A7%C3%A3o%20de%20Contexto.md

- [x] Introdução
- [x] Problema
- [x] Objetivos
- [x] Justificativa
- [x] Público-Alvo

**Comment by EdmilsonSCCP** [comment]
Adicionei a introdução e o problema.

**Comment by EdmilsonSCCP** [comment]
Adicionei os objetivos.

**Comment by caarlos1** [comment]
Tarefa finalizada!
