### ISSUE TITLE
Atualizar "02-Especificação do Projeto.md" de acordo com o documento do Projeto

### ISSUE THREAD

**Issue by caarlos1** [ICEI-PUC-Minas-PMV-ADS/pmv-ads-2023-2-e1-proj-web-t5-doe-facil#3]
Link do arquivo:
https://github.com/ICEI-PUC-Minas-PMV-ADS/pmv-ads-2023-2-e1-proj-web-t5-doe-facil/blob/main/documentos/02-Especifica%C3%A7%C3%A3o%20do%20Projeto.md

- [x] Perfis de Usuários
- [x] Histórias de Usuários
- [x] Requisitos Funcionais
- [x]  Requisitos não Funcionais

**Comment by caarlos1** [comment]
Atualizei os Perfis de Usuário

**Comment by caarlos1** [comment]
Atualizei os "Requisitos Funcionais".

**Comment by figueiredobarbara** [comment]
Atualizei a tabela de histórias de usuários.

**Comment by figueiredobarbara** [comment]
Atualizei a tabela de requisitos não funcionais.

**Comment by caarlos1** [comment]
Tarefa finalizada.
